# Site settings
title: blogballs
description: An attempt at a blog that I will no-doubt fail to update.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hogballs.dev" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Plugins
plugins:
  - jekyll-feed

# Pagination
paginate: 50
paginate_path: "/page:num/"

# Syntax highlighting
kramdown:
  syntax_highlighter: rouge
